name: asl_edgedec_pictures
description: "ASL Edge Detector from Pictures"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  image: ^4.2.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  permission_handler_android: ^13.0.1
  device_info_plus: ^12.2.0
  flutter_file_dialog: ^3.0.2
  image_picker: ^1.2.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "icons/ICON_PICTURE.png"

  assets:
    - icons/ICON_PICTURE.png